Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-18.04"

    config.vm.define :bucket do |bucket_config|

        bucket_config.vm.network "private_network", ip: "192.168.50.11"
        bucket_config.vm.hostname = 'bucket'

        bucket_config.vm.provider :virtualbox do |vb|
            vb.name = "bucket"
        end

        bucket_config.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/ssh-connections.yaml"
		end

    end

end